[package]
name = "log_view"
version = "0.33.0"
edition = "2021"

publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_inspect = { path = "../../egui_inspect", features = ["logging"] }
better_default = "1.0.5"
