[package]
name = "egui_inspect_wrap"
version = "0.33.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_inspect = { path = "../egui_inspect" }
